site_name: Chaincue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
use_directory_urls: true
#extra_css:
#  - stylesheets/extra.css
#extra_javascript:
#  - javascripts/extra.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://chaincuet.com/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  custom_dir: overrides
  logo: assets/static/favicon.ico
  favicon: assets/static/favicon.ico
  palette:
    scheme: default
    primary: blue grey
    accent: deep purple
  features:
    - navigation.tabs
    - header.autohide
  include_sidebar: true

nav:
  - Welcome:
      - "": index.md
  - DevOps:
      - Overview: devops/index.md
      - AWS | VPC: devops/aws-vpc.md
      - AWS | S3 & Cloudfront: devops/s3-cloudfront.md
      - AWS | Route53: devops/route53.md
      - AWS | Lambda & API Gateway: devops/aws-lambda-api-gateway.md
      - AWS | ECS/ECR: devops/ecs.md
      - AWS | DynamoDB: devops/dynamoDB.md
      - AWS | VPN: devops/vpn.md
      - Azure | Storage: devops/az-storage.md
      - Azure | Cosmos DB: devops/az-cosmosdb.md
      - Azure | Active Directory: devops/az-default-directory.md
      - Terraform: devops/terraform.md
      - Nginx: devops/nginx.md
      - Vault: devops/vault.md
      - Keycloak: devops/keycloak.md
      - Bitwarden: devops/bitwarden.md
      - Wireguard: devops/wireguard.md
      - Email: devops/email.md
      - Gitlab: devops/gitlab.md
      - Github: devops/github.md
      - Slack: devops/slack.md
  - Docker & Kubernetes:
      - Overview: docker-kubernetes/index.md
      - Docker: docker-kubernetes/docker.md
      - Kubernetes Production: docker-kubernetes/kubernetes-production.md
      - Kubernetes Commands: docker-kubernetes/kubernetes-commands.md
      - Microk8s: docker-kubernetes/microk8s.md
      - k9s: docker-kubernetes/k9s.md
  - Backend:
      - Overview: backend/index.md
      - Java: backend/java.md
      - Kotlin: backend/kotlin.md
      - C#: backend/c#.md
      - Go: backend/go.md
      - Rust: backend/rust.md
      - Python: backend/python.md
      - Express: backend/express.md
      - Spring Cloud: backend/spring-cloud.md
      - Reactive IO: backend/reactiveio.md
  - Frontend:
      - Overview: frontend/index.md
      - Npm: frontend/npm.md
      - HTML: frontend/html.md
      - CSS Styling: frontend/css-styling.md
      - Javascript & Typescript: frontend/javascript-typescript.md
      - NextJS: frontend/nextjs.md
      - Gists: frontend/gists.md
      - Flutter: frontend/flutter.md
      - Angular: frontend/angular.md
  - AI / ML:
      - Overview: ai/index.md
      - OpenAI: ai/openAI.md
      - Ollama: ai/ollama.md
      - TensorFlow: ai/tensorflow.md
      - PyTorch: ai/pytorch.md
  - Databases:
      - Overview: databases/index.md
      - Postgres: databases/postgres.md
      - Mysql: databases/mysql.md
      - MongoDB: databases/mongodb.md
      - Redis: databases/redis.md
  - Blockchain:
      - Overview: blockchain/index.md
      - Ethereum: blockchain/ethereum.md
      - BNB Chain: blockchain/bnb.md
      - Hyperledger: blockchain/hyperledger.md
  - Linux:
      - Overview: linux/index.md
      - Aliases: linux/alias.md
  - Windows:
      - Overview: windows/index.md
      - Aliases: windows/alias.md
      - Unreal Engine: windows/unreal_engine.md
  - Utils:
      - Overview: utils/index.md
      - Emoji: utils/emoji.md
      - Git: utils/git.md
      - IDEs: utils/ides.md
      - SSH: utils/ssh.md
      - ffmpeg: utils/ffmpeg.md
      - imagemagick: utils/imagemagick.md
  - Randoms:
      - Overview:  randoms/index.md
      - Music: randoms/music.md
      - Universe Sandbox: randoms/universe-sandbox.md
