site_name: Chaincue Technologies Docs
repo_url: https://github.com/KQT3/chaincuet-wiki
use_directory_urls: true
#extra_css:
#  - stylesheets/extra.css
#extra_javascript:
#  - javascripts/extra.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://chaincuet.com/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  custom_dir: overrides
  logo: assets/static/favicon.ico
  favicon: assets/static/favicon.ico
  palette:
    scheme: default
    primary: blue grey
    accent: deep purple
  features:
    - navigation.tabs
    - header.autohide
  include_sidebar: true

nav:
  - Welcome:
      - "": index.md
  - DevOps:
      - Overview: devops/index.md
      - AWS | S3 & Cloudfront: devops/s3-cloudfront.md
      - AWS | Route53: devops/route53.md
      - AWS | Lambda & API Gateway: devops/aws-lambda-api-gateway.md
      - AWS | ECS/ECR: devops/ecs.md
      - AWS | DynamoDB: devops/dynamoDB.md
      - AWS | VPN: devops/vpn.md
      - Azure | Storage: devops/az-storage.md
      - Azure | Cosmos DB: devops/az-cosmosdb.md
      - Azure | Active Directory: devops/az-default-directory.md
      - Terraform: devops/terraform.md
      - Nginx: devops/nginx.md
      - Vault: devops/vault.md
      - Keycloak: devops/keycloak.md
      - Email: devops/email.md
      - Wireguard: devops/wireguard.md

  - Docker & Kubernetes:
      - Overview: docker-kubernetes/index.md
      - Docker: docker-kubernetes/docker.md
      - Kubernetes Commands: docker-kubernetes/kubernetes-commands.md
      - Kubernetes Production: docker-kubernetes/kubernetes-production.md
  - Java / Spring Cloud:
      - Spring Cloud Overview: java-spring-cloud/index.md
      - Domains: java-spring-cloud/domains.md
      - Services: java-spring-cloud/services.md
      - Tracing: java-spring-cloud/tracing.md
      - Reactive IO: java-spring-cloud/reactiveio.md
      - Concurrency: java-spring-cloud/concurrency.md
  - Frontend:
      - Node: frontend/index.md
      - HTML: frontend/html.md
      - CSS Styling: frontend/css-styling.md
      - Javascript & Typescript: frontend/javascript-typescript.md
      - Gists: frontend/gists.md
  - AI / ML:
      - Overview: ai/index.md
      - OpenAI: ai/openAI.md
      - TensorFlow: ai/tensorflow.md
      - PyTorch: ai/pytorch.md
  - Databases:
      - Database Overview: databases/index.md
      - Postgres: databases/postgres.md
      - Mysql: databases/mysql.md
      - MongoDB: databases/mongodb.md
      - Redis: databases/redis.md
  - Blockchain:
      - Overview: blockchain/index.md
      - Ethereum: blockchain/ethereum.md
      - BNB Chain: blockchain/bnb.md
      - Hyperledger: blockchain/hyperledger.md
  - Linux:
      - Overview: linux/index.md
      - Alias: linux/alias.md
  - Utils:
      - Utils Overview: utils/index.md
      - Emoji: utils/emoji.md
      - Git: utils/git.md
      - Go: utils/go.md
      - Python: utils/python.md
      - IDEs: utils/ides.md
